### ISSUE TITLE
Error when header value contains colon

### ISSUE THREAD

**Issue by andresesfm** [artssec/burp-exporter#4]
**Burp Suite Version:**
v2020.9.2 Communuty Edition 
**Description:**
When trying to export a request that contains headers with ":" in the body, there's an exception thrown complaining about attempting to create a dict with more than the expected two elements per subarray
**Steps or PoCs:**

**HTTP(s) Requests/Responses:**
MY_HEADER: {"param":"val"}
**Screenshots:**

The following PR fixes the issue and cleans up duplicate code to convert headers to a new dict: https://github.com/artssec/burp-exporter/pull/3

**Comment by artssec** [comment]
Hi @andresesfm thanks for sharing, validated the fix.

**Comment by artssec** [comment]
LGTM. Merged
