### ISSUE TITLE
lost '\' when copy as python requests

### ISSUE THREAD

**Issue by maybe-why-not** [artssec/burp-exporter#5]
**Burp Suite Version:**
4:22 am 2020.11.20
**Description:**
lost '\\' when copy as python requests
**Steps or PoCs:**

**HTTP(s) Requests/Responses:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/29968903/99744097-fc2a4880-2b11-11eb-889a-eb7d4e04897a.png)

**Comment by artssec** [comment]
Fixed! Thank you so much!

**Comment by maybe-why-not** [comment]
No fixed
![image](https://user-images.githubusercontent.com/29968903/137055035-80dc9cbf-0fcd-4e7c-b383-fad80ef0d1c6.png)
