### ISSUE TITLE
Multiple code fixes, Code was tested

### ISSUE THREAD

**Issue by winezer0** [artssec/burp-exporter#6]
This is the code address：
[Exporter-20201219-modify.txt](https://github.com/artssec/burp-exporter/files/5719440/Exporter-20201219-modify.txt)

First of all, I'm sorry That I don't use Git, so I can only send you the modified source code in text
Add HTTPS support to all generated scripts and fix some syntax errors.  except for javascript module errors
Here are some of the changes:
python requests https  error has been fixed
Golang Native HTTPS and syntax errors have been fixed
Powershell HTTPS and syntax errors have been fixed
Perl LWP HTTPS and cookie string cutting errors have been fixed
The NodeJS HTTPS error has been fixed
php http_request2   HTTPS error has been fixed
jquery ajax  by module  generated code was not usable, but I did not fix it

Other issues: 
Support for other POST request formats is not particularly friendly, such as json format not being escaped

这里是代码地址：
[Exporter-20201219-modify.txt](https://github.com/artssec/burp-exporter/files/5719440/Exporter-20201219-modify.txt)
首先，很抱歉，我不会使用git,所以我只能用文本的方法发送修改好的源码给您
给所有生成的脚本添加HTTPS支持，并修复部分语法错误。 除了javascript模块的错误
以下是一些变化:
python requests  https错误 已修复
Golang Native  HTTPS和语法错误 已修复
Powershell HTTPS和语法错误 已修复
Perl LWP HTTPS和cookie字符串切割错误 已修复
NodeJS HTTPS错误 已修复
php http_request2 HTTPS错误 已修复
jquery ajax 模块生成的代码不能用，但我没有修复它
其他问题：
对于其他的post请求格式支持不是特别友好，例如json格式没有被转义

**Comment by artssec** [comment]
Fixed! Thank you so much!
